name: Deploy Server to EC2

on:
  push:
    branches:
      - main
    paths:
      - "apps/server/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "turbo.json"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            cd ${{ secrets.EC2_PATH }}
            git pull origin main

            # Use correct Node version
            source ~/.nvm/nvm.sh
            nvm use 22

            # Install only server-related dependencies
            pnpm install --filter server...

            # Build only the server package
            pnpm turbo run build --filter=server

            # Restart the server using PM2
            pm2 restart server || pm2 start apps/server/dist/index.js --name server

            pm2 save
          EOF
